inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'exe/**/*'
    - 'fixtures/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'

Metrics/AbcSize:
  Enabled: false
  Exclude:
    - test/**/*

Metrics/ClassLength:
  Exclude:
    - test/**/*

Metrics/LineLength:
  Exclude:
    - features/step_definitions/**/*

Metrics/MethodLength:
  Exclude:
    - test/**/*

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

# Prefer { ... } over do ... end except for control flow and
# method defintions. Unfortunatly, no cop configuration for this.
# https://github.com/chneukirchen/styleguide/blob/e60de37b478d3f892f6985a58d573016f33f0269/RUBY-STYLE#L63-L67
Style/BlockDelimiters:
  EnforcedStyle: semantic
  Enabled: false

# Generally prefer compact style to reduce indentation. But no hard rule.
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  Enabled: false

# TODO(thomthom): Consider turning this back on.
Style/Documentation:
  Enabled: false

# It's ok to have more than one empty line to create a 'paragrapth'.
Style/EmptyLines:
  Enabled: false

Style/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines_except_namespace

Style/EmptyLinesAroundModuleBody:
  EnforcedStyle: empty_lines_except_namespace

# Add lines as needed.
Style/EmptyLinesAroundBlockBody:
  Enabled: false

# Rely on Git to normalize end of lines.
Style/EndOfLine:
  Enabled: false

# Conflict too often with Metric/LineLength.
# https://github.com/bbatsov/rubocop/issues/1332#issuecomment-277503854
Style/GuardClause:
  Enabled: false

# Add trailing comma so it's easy to duplicate/add lines.
Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: consistent_comma
